### ISSUE TITLE
SQL Query Incorrect

### ISSUE THREAD

**Issue by Rage-GitHub** [ESX-PUBLIC/esx_DarkShops#2]
The .sql file provided was not matching the **server.lua** code to pull the items from the list. I've fixed it and added it into the query, please keep track of this stuff next time.

https://drive.google.com/open?id=13Jymjaj72WSqhPJyZxnR5GmCaNYwr-C6

**Comment by ElPumpo** [comment]
Why have you linked a file instead of doing a pull request????

**Comment by Rage-GitHub** [comment]
> Why have you linked a file instead of doing a pull request????

![image](https://user-images.githubusercontent.com/17907584/50551105-0f944800-0c4a-11e9-8feb-93825319eff0.png)

I can't open a pull request because it complains about needing a separate branch from the master branch.

**Comment by Rage-GitHub** [comment]
By the way, the item listing Dark in the table for **darkshops** should not be in there at all if the resource doesn't add it in because it will cause the table/shop in-game to mess up and not work.
