### ISSUE TITLE
No items listed

### ISSUE THREAD

**Issue by TriumphantToast** [ESX-PUBLIC/esx_DarkShops#4]
I have followed the recommendation of changing 'item' to 'items' in the db but i am still unable to see any items listed in the store. I am getting this error in the console: 

"Cannot read property 'ScrollIntoView' of Undefined" (esx_menu_default/html/js/app.js:69)

Is there a known issue with ESX's menu?

**Comment by ElPumpo** [comment]
it means that the menu is empty. not a bug

**Comment by TriumphantToast** [comment]
Not sure why you would close this that quickly. The menu should not be empty and there are items in the database, including your "darknet" item that comes with the mod.

**Comment by mwasif02** [comment]
@jon-weiss did it got solved for you?
